// <auto-generated />
using System;
using Eventask.ApiService.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eventask.ApiService.Migrations
{
    [DbContext(typeof(EventaskContext))]
    [Migration("20251218130053_BackendOverhaul")]
    partial class BackendOverhaul
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.CalendarMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CalendarId", "UserId")
                        .IsUnique();

                    b.ToTable("CalendarMember");
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.ScheduleItems.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OffsetMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScheduleItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleItemId");

                    b.ToTable("Reminder");
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.ScheduleItems.ScheduleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("ScheduleItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("ScheduleItems");

                    b.HasDiscriminator<string>("ScheduleItemType").HasValue("ScheduleItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.ScheduleItems.ScheduleEvent", b =>
                {
                    b.HasBaseType("Eventask.Domain.Entity.Calendars.ScheduleItems.ScheduleItem");

                    b.Property<bool>("AllDay")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Event");
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.ScheduleItems.ScheduleTask", b =>
                {
                    b.HasBaseType("Eventask.Domain.Entity.Calendars.ScheduleItems.ScheduleItem");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Task");
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.Calendar", b =>
                {
                    b.HasOne("Eventask.Domain.Entity.Users.User", null)
                        .WithMany("Calendars")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.CalendarMember", b =>
                {
                    b.HasOne("Eventask.Domain.Entity.Calendars.Calendar", "Calendar")
                        .WithMany("Members")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventask.Domain.Entity.Users.User", null)
                        .WithMany("CalendarMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.ScheduleItems.Reminder", b =>
                {
                    b.HasOne("Eventask.Domain.Entity.Calendars.ScheduleItems.ScheduleItem", "ScheduleItem")
                        .WithMany("Reminders")
                        .HasForeignKey("ScheduleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleItem");
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.ScheduleItems.ScheduleItem", b =>
                {
                    b.HasOne("Eventask.Domain.Entity.Calendars.Calendar", "Calendar")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Eventask.Domain.Entity.Calendars.ScheduleItems.Attachment", "Attachments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("ScheduleItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Sha256")
                                .HasColumnType("text");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Version")
                                .IsConcurrencyToken()
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("ScheduleItemId");

                            b1.ToTable("Attachments");

                            b1.WithOwner("ScheduleItem")
                                .HasForeignKey("ScheduleItemId");

                            b1.Navigation("ScheduleItem");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.ScheduleItems.ScheduleEvent", b =>
                {
                    b.OwnsOne("Eventask.Domain.Entity.Calendars.ScheduleItems.RecurrenceRule", "RecurrenceRule", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("ByDay")
                                .HasColumnType("text");

                            b1.Property<int?>("Count")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Freq")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Interval")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(1);

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("ScheduleItemId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("Until")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Version")
                                .IsConcurrencyToken()
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("ScheduleItemId")
                                .IsUnique();

                            b1.ToTable("RecurrenceRules", (string)null);

                            b1.WithOwner("ScheduleItem")
                                .HasForeignKey("ScheduleItemId");

                            b1.Navigation("ScheduleItem");
                        });

                    b.Navigation("RecurrenceRule");
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.Calendar", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("ScheduleItems");
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Calendars.ScheduleItems.ScheduleItem", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("Eventask.Domain.Entity.Users.User", b =>
                {
                    b.Navigation("CalendarMemberships");

                    b.Navigation("Calendars");
                });
#pragma warning restore 612, 618
        }
    }
}
